### ISSUE TITLE
지금까지 나왔던 디자인 패턴

### ISSUE THREAD

**Issue by devSoyoung** [devSoyoung/2019-KHU-spring-study#9]
## 디자인패턴 목록
* [전략 패턴](https://github.com/devSoyoung/2019-KHU-spring-study/issues/9#issuecomment-493749763)
* [데코레이터 패턴](https://github.com/devSoyoung/2019-KHU-spring-study/issues/9#issuecomment-493749812)
* 어댑터 패턴 
* 프록시 패턴
* 템플릿 콜백 패턴
* 싱글톤 패턴

**Comment by devSoyoung** [comment]
## 전략패턴

**Comment by euidong** [comment]
## 데코레이터 패턴
